name: CI for Push and Pull Request

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install npm dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm run test